
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20141204 (SVN rev 60)
//----------------------------------------------------

package cup.example;

/** CUP generated interface containing symbol constants. */
public interface sym {
    /* terminals */
    public static final int DOUBLEDOT = 7;
    public static final int REAL = 28;
    public static final int GT = 20;
    public static final int PACKED = 65;
    public static final int TYPE = 76;
    public static final int CONST = 39;
    public static final int ASM = 36;
    public static final int GE = 21;
    public static final int UNTIL = 78;
    public static final int CONSTRUCTOR = 40;
    public static final int COMMA = 8;
    public static final int LT = 18;
    public static final int INTEGER = 27;
    public static final int LBRA = 15;
    public static final int SHR = 72;
    public static final int FALSE = 47;
    public static final int NOT = 61;
    public static final int LE = 19;
    public static final int NIL = 60;
    public static final int ARRAY = 35;
    public static final int SHL = 71;
    public static final int OBJECT = 62;
    public static final int VAR = 80;
    public static final int INLINE = 56;
    public static final int THEN = 73;
    public static final int GOTO = 52;
    public static final int STR = 32;
    public static final int RECORD = 68;
    public static final int MOD = 59;
    public static final int RBRA = 16;
    public static final int MULTIPLY = 4;
    public static final int TRUE = 75;
    public static final int PLUS = 2;
    public static final int DIVIDE = 5;
    public static final int UNIT = 77;
    public static final int WHILE = 81;
    public static final int LPAR = 13;
    public static final int EQUAL = 22;
    public static final int IMPLEMENTATION = 54;
    public static final int ASSIGN = 12;
    public static final int INTERFACE = 57;
    public static final int CHAR = 26;
    public static final int BOOLEAN = 25;
    public static final int DO = 43;
    public static final int FOR = 49;
    public static final int DIV = 42;
    public static final int DOWNTO = 44;
    public static final int ELSE = 45;
    public static final int DOT = 6;
    public static final int PROCEDURE = 66;
    public static final int EOF = 0;
    public static final int SEMICOLON = 10;
    public static final int COMMENT = 33;
    public static final int RPAR = 14;
    public static final int FOWARD = 50;
    public static final int FUNCTION = 51;
    public static final int REPEAT = 69;
    public static final int LABEL = 58;
    public static final int MINUS = 3;
    public static final int NUMINT = 84;
    public static final int DESTRUCTOR = 41;
    public static final int IN = 55;
    public static final int OR = 64;
    public static final int SET = 70;
    public static final int error = 1;
    public static final int DIFF = 23;
    public static final int SINGLEQUOTES = 17;
    public static final int CHR = 31;
    public static final int IF = 53;
    public static final int ID = 30;
    public static final int OF = 63;
    public static final int END = 46;
    public static final int COLON = 9;
    public static final int FILE = 48;
    public static final int NUMREAL = 85;
    public static final int CARET = 11;
    public static final int BEGIN = 37;
    public static final int CASE = 38;
    public static final int STRING = 29;
    public static final int PROGRAM = 67;
    public static final int AND = 34;
    public static final int SIGN = 24;
    public static final int TO = 74;
    public static final int WITH = 82;
    public static final int XOR = 83;
    public static final int USES = 79;
    public static final String[] terminalNames = new String[] {
            "EOF",
            "error",
            "PLUS",
            "MINUS",
            "MULTIPLY",
            "DIVIDE",
            "DOT",
            "DOUBLEDOT",
            "COMMA",
            "COLON",
            "SEMICOLON",
            "CARET",
            "ASSIGN",
            "LPAR",
            "RPAR",
            "LBRA",
            "RBRA",
            "SINGLEQUOTES",
            "LT",
            "LE",
            "GT",
            "GE",
            "EQUAL",
            "DIFF",
            "SIGN",
            "BOOLEAN",
            "CHAR",
            "INTEGER",
            "REAL",
            "STRING",
            "ID",
            "CHR",
            "STR",
            "COMMENT",
            "AND",
            "ARRAY",
            "ASM",
            "BEGIN",
            "CASE",
            "CONST",
            "CONSTRUCTOR",
            "DESTRUCTOR",
            "DIV",
            "DO",
            "DOWNTO",
            "ELSE",
            "END",
            "FALSE",
            "FILE",
            "FOR",
            "FOWARD",
            "FUNCTION",
            "GOTO",
            "IF",
            "IMPLEMENTATION",
            "IN",
            "INLINE",
            "INTERFACE",
            "LABEL",
            "MOD",
            "NIL",
            "NOT",
            "OBJECT",
            "OF",
            "OR",
            "PACKED",
            "PROCEDURE",
            "PROGRAM",
            "RECORD",
            "REPEAT",
            "SET",
            "SHL",
            "SHR",
            "THEN",
            "TO",
            "TRUE",
            "TYPE",
            "UNIT",
            "UNTIL",
            "USES",
            "VAR",
            "WHILE",
            "WITH",
            "XOR",
            "NUMINT",
            "NUMREAL"
    };
}

